# Версия docker-compose
version: '3.8'

# Создаем отдельные контейнеры
services:
    # контейнер с nginx
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        volumes:
            # папка с проектом
            - ../app:/var/www/app
            # конфиг для nginx
            - "./nginx:/etc/nginx/conf.d"
            # папка с логами
            - ./storage/log/nginx:/var/log/nginx
        ports:
            - "80:80"
        depends_on:
            - php-fpm
        # Подключаем к общей сети с другими контейнерами
        networks:
            - default
    # Контейнер с менеджером php
    php-fpm:
        build:
            context: .
            dockerfile: php-fpm.dockerfile
        volumes:
            - ../app:/var/www/app
        depends_on:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
        ports:
            - "9000:9000"
        # Подключаем к общей сети с другими контейнерами
        networks:
            - default
    # Контейнер с базой данных
    mysql:
        image: mysql:8
        # подключаем папку для хранения БД
        volumes:
            - ./storage/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=app"
            - "MYSQL_DATABASE=app"
        ports:
            - "3306:3306"
        # Подключаем к общей сети с другими контейнерами
        networks:
            - default
    # Контейнер с redis
    redis:
        image: redis:3.0
        volumes:
        - ./storage/redis:/data
        ports:
            - "6379:6379"
        # Подключаем к общей сети с другими контейнерами
        networks:
            - default
    # Контейнер с phpmyadmin
    phpmyadmin:
        build:
            context: .
            dockerfile: phpmyadmin.dockerfile
        # Add volume for sessions to allow session persistence
        volumes:
        - ./storage/phpmyadmin/sessions:/sessions
        ports:
            - "8080:80"
        depends_on:
            - mysql
        environment:
            - VIRTUAL_HOST=phpmyadmin.test
            - PMA_HOST=mysql
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - default

# Создаем общую сеть deafult для всех контейнеров
networks:
    default:
        driver: bridge
